# Generated by Django 2.2 on 2019-05-21 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=3)),
                ('descripcion', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'banco',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('calle', models.CharField(blank=True, max_length=45, null=True)),
                ('colonia', models.CharField(blank=True, max_length=45, null=True)),
                ('delegacion', models.CharField(blank=True, max_length=45, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=45, null=True)),
                ('estado', models.CharField(blank=True, max_length=45, null=True)),
                ('cp', models.CharField(blank=True, max_length=5, null=True)),
                ('regimen', models.CharField(blank=True, max_length=45, null=True)),
                ('rfc', models.CharField(blank=True, max_length=13, null=True)),
                ('fecha_constitucion', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'condominio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CuentaContable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_cuenta', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=100)),
                ('clave_mayor', models.CharField(max_length=4)),
            ],
            options={
                'verbose_name_plural': 'Cuentas contables',
                'db_table': 'cuenta_contable',
                'ordering': ['num_cuenta'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PeriodoCorte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicial', models.DateField(blank=True, null=True)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True)),
                ('fecha_final', models.DateField(blank=True, null=True)),
                ('saldo_final', models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Catalogos.Condominio')),
            ],
            options={
                'db_table': 'periodo_corte',
                'managed': True,
            },
        ),
    ]
