# Generated by Django 2.2 on 2019-05-21 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='condominio',
            options={'managed': True, 'verbose_name_plural': 'Datos del condominio'},
        ),
    ]
